# Generated by Django 4.2.7 on 2025-06-08 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinfo",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_infos",
                to="users.supplier",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="shop.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="shop.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="shop.productinfo",
                verbose_name="Информация о товаре",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="users.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="users.contact",
                verbose_name="Контакт для заказа",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="shop.cart",
                verbose_name="Корзина",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.productinfo",
                verbose_name="Информация о товаре",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to="users.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productparameter",
            unique_together={("product_info", "parameter")},
        ),
        migrations.AlterUniqueTogether(
            name="productinfo",
            unique_together={("product", "supplier")},
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "product_info")},
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product_info")},
        ),
    ]
